name: launcher
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_apps: ^1.2.0
  percent_indicator: ^4.0.1
  google_fonts: ^4.0.0
  intl: ^0.18.0
  battery_plus: ^3.0.3
  url_launcher: ^6.1.10
  launcher_assist: ^1.1.3
  android_intent: ^2.0.2
  flutter_bloc: ^8.1.2
  uninstall_apps: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/
